
package us.kardol.soap.client.wsimport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPResourceService", targetNamespace = "http://service.soap.kardol.us/", wsdlLocation = "http://localhost:8888/testsoap?wsdl")
public class SOAPResourceService
    extends Service
{

    private final static URL SOAPRESOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPRESOURCESERVICE_EXCEPTION;
    private final static QName SOAPRESOURCESERVICE_QNAME = new QName("http://service.soap.kardol.us/", "SOAPResourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/testsoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPRESOURCESERVICE_WSDL_LOCATION = url;
        SOAPRESOURCESERVICE_EXCEPTION = e;
    }

    public SOAPResourceService() {
        super(__getWsdlLocation(), SOAPRESOURCESERVICE_QNAME);
    }

    public SOAPResourceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPRESOURCESERVICE_QNAME, features);
    }

    public SOAPResourceService(URL wsdlLocation) {
        super(wsdlLocation, SOAPRESOURCESERVICE_QNAME);
    }

    public SOAPResourceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPRESOURCESERVICE_QNAME, features);
    }

    public SOAPResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPResource
     */
    @WebEndpoint(name = "SOAPResourcePort")
    public SOAPResource getSOAPResourcePort() {
        return super.getPort(new QName("http://service.soap.kardol.us/", "SOAPResourcePort"), SOAPResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPResource
     */
    @WebEndpoint(name = "SOAPResourcePort")
    public SOAPResource getSOAPResourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.kardol.us/", "SOAPResourcePort"), SOAPResource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPRESOURCESERVICE_EXCEPTION!= null) {
            throw SOAPRESOURCESERVICE_EXCEPTION;
        }
        return SOAPRESOURCESERVICE_WSDL_LOCATION;
    }

}
